### ISSUE TITLE
Lift code to be a class method of the model & remove this functionality from bequeath_all

### ISSUE THREAD

**Issue by jackdeath5** [BirdLogics/expertiza#7]
Line 112-114: In the inherit method, the code that copies a list would be better placed as a class method of the Team model. Also, give a better intuitive name to the method depending on its functionality. This part is also duplicated in the method bequeath_all, remove that after abstracting it in a method.

**Comment by BirdLogics** [comment]
https://github.com/BirdLogics/expertiza/blob/85ac4d26de490823850113a7ca23625114b5ebde/app/controllers/teams_controller.rb#L112
https://github.com/BirdLogics/expertiza/blob/85ac4d26de490823850113a7ca23625114b5ebde/app/controllers/teams_controller.rb#L121
